# 언어와 jdk의 버전 지정
language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# 빌드전에 gradlew의 권한 추가
before_install:
  - chmod +x gradlew

# Travis CI 서버의 HOME
# gradle을 통하여 의존성을 받게 되면 이를 캐시하여 배포할 때마다 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브랜치에 push 되면 수행되는 명령어이다.
# 프로젝트 내에 권한이 추가된 gradlew를 활용하여 clean, build를 진행한다.
script: "./gradlew clean build"

# CI 실행 완료 시 작성한 이메일로 알람
notifications:
  slack:
    on_success: always
    on_failure: always
    studycommpany:W1gOLioFUZEtMCkvRrdo8yZ1
  email:
    recipients:
      - cksgml4424@gmail.com